### ISSUE TITLE
It was not working 

### ISSUE THREAD

**Issue by Rahul123456789mondal** [vladan29/internet_checker#1]
var internetManager: InternetManager? = null
    private var isConnected = false
    private val networkLiveData = NetworkLiveData.get()

// Using The library
        internetManager = InternetManager.getInternetManager(this);
        internetManager!!.registerInternetMonitor()

        networkLiveData.observe(this@MainActivity) { networkState ->
            isConnected = networkState.isConnected
        }

        if (isConnected){
            activityBinding.textV.text = "Connected to Internet"
            activityBinding.textV.setTextColor(Color.BLACK)
        }else{
            activityBinding.textV.text = "No Internet Connection"
            activityBinding.textV.setTextColor(Color.RED)
        }

**Comment by vladan29** [comment]
I can't see where you registered internetMonitor. In the documentation is a suggestion to do this in the Application class. The next question is in which method of the activity or fragment you start the observer.
And advice-> Use  private lateinit var internetManager: InternetManager to avoid null checking.
example:
@HiltAndroidApp
class MyApp: Application(){
    private lateinit var internetManager: InternetManager
    override fun onCreate() {
        super.onCreate()
        internetManager = InternetManager.getInternetManager(this)
        internetManager.registerInternetMonitor()
    }
}

@AndroidEntryPoint
class MainActivity : AppCompatActivity() {
-
-
-
private val networkLiveData: NetworkLiveData = NetworkLiveData.get()

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
       
        observeNetworkConnection()

}


//With the following code you will observe Connection changes.
//With your code you only change the value of private var isConnected = false, but that value is not observed.
//If you start debugger you will see that library works, and private var isConnected is changed but your code doesn't work.
  private fun observeNetworkConnection() {
        networkLiveData.observe(this) {
        
                if (!it.isConnected) {
                    setTextInTextView(it.isConnected)
                }
           
        }
    }

**Comment by vladan29** [comment]
There is no issue on the library side.
