### ISSUE TITLE
How to check Internet Connection in Background continuously even if App is Running or Not/Closed..

### ISSUE THREAD

**Issue by patelakshay13890** [vladan29/internet_checker#2]
How Check Internet Connection in Broadcast Receiver or Service Like as we do in Activity ?
But I need in Service or Broadcast Receiver..
Means I need to check Internet Connation in Background continuously even if App is Running or Not/Closed..
As on Internet Connectivity change I want to Sync My Data to Server so please help me out..!!
Thanks..

**Comment by vladan29** [comment]
This library can't be used for classes that are not "view"(foreground) classes. By default, LiveData can't be observed in the background.
For that usage, you can refactor code from this library using interfaces instead LiveData. In the code, NetworkStateListener already exists. Use it instead LiveData and implement it as an interface or listener.
